### ISSUE TITLE
Pause/enable/disable buttons are misleading

### ISSUE THREAD

**Issue by arnemertz** [veger/TLBE#15]
In UIs, buttons usually are labeled with what they do, e.g. a pause label when something is playing and can be paused, a play label when something is paused and can be activated. Instead, in TLBE, the enable/disable buttons for cameras and trackers, as well as the "pause game when this window is open" button, are labeled with the current _state_, i.e. exactly reversed.

The Factorio GUI library has Items that I think are better suited for "enable/disable" controls. I would suggest a switch with "allow_none_state" set to False.

**Comment by veger** [comment]
Thank you for your feedback! :+1: 

I tried to keep the UI compact, and a switch with a label attached (becaue without it would be confusing), takes considerably more space. (and with the pause game button in the title bar it is even weirder I guess)

Also, I wonder if showing the 'action' instead of the 'state' is more clear? :thinking: When you look at the UI you'd like to see its settings/configuration ('state') in a single overview. At least this is what I would expect for a settings-like UI.

Maybe this would help a little:
1. replace the play/pause icons (for the camera/tracker) with an 'sprite button that toggles'. Then the state/action might be more clear. (I used stock icons and I am not a 'good artist' :wink: )
1. only show delete camera/tracker when the action is available
1. Pause game toggles without changing its sprite (only use pause sprite)

Do you think this would improve/help the UI?

**Comment by arnemertz** [comment]
If I understand you correctly, the sprite button that toggles would e.g. just display the pause icon and have a "pressed" (= paused/disabled) and "not pressed" (enabled) state? Or the other way round with a play icon? That sounds good.
You could, in addition, display the current state of cameras and trackers (enabled/disabled) as a string in the properties list on the right.

I haven't had much time to use the mod yet, but it looks promising and easy to use once I've cleared the "is it recording now?" hurdle 🥇

**Comment by veger** [comment]
yes, instead of changing the sprite/image they would only show 'pressed' vs 'not pressed'.

**Comment by veger** [comment]
GUI should be improved on next release according to discussion above (and some other things I found while fixing)
