### ISSUE TITLE
Resolution doesn't effect zoomlevel. Possible Bug.

### ISSUE THREAD

**Issue by roplesk** [veger/TLBE#25]
If I change the resolution of the screenshots to 2x the resultion (4096x2160), the viewing distange of the shot becomes 2x larger and the zoomlevel stay constant.

This means the factory is effectfly 2x smaller on the picture, but same level of details.

Here are two consequative frames (scaled down for github).
where inbetween the resolution was changed.

The zoom level does not reduces after playing for longer.
![00000204-main](https://user-images.githubusercontent.com/35077403/126493548-054cf8f0-0243-4784-bb49-0dda081ec26f.jpg)
![00000205-main](https://user-images.githubusercontent.com/35077403/126493553-4c415e3b-9e7b-4bbb-b8c6-245d63751099.jpg)

PS: Thank you for this great mod.

**Comment by veger** [comment]
The zoom level (and its behavior) is determined by the active tracker.The base tracker and the area tracker should adjust their zoom level to make sure that a certain area (the base or the provided coordinates) stays within the screenshots. So I agree it is a bug that those two should adjust their zoom level when one changes the resolution. (Although this is pretty hard to do properly, as the camera might be zooming in/out at the same time...).

Note that for the rocket launch tracker and the player tracker the zoom level is constant (maximum zoomed in).

Since you didn't specify which tracker was active when you made the screenshots, I'll assume it is one of the first two?

**Comment by veger** [comment]
I noticed a minor difference in area that is in the screenshot after changing resolution.
Zoom level seemed to be calculated correctly, so I think Factorio itself takes the screenshot slightly different (due to changed zoom level)

**Comment by veger** [comment]
Released in v1.4.2
